# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate Dataset Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Java JDK
      uses: actions/setup-java@v4.5.0
      with:
        # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
        java-version: 21
        distribution: temurin

    - name: Setup Graphviz
      run: sudo apt-get install -y graphviz 
      
    - name: Run generate.sh
      run: ./generate.sh

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: dataset_build
        path: ./gen
        retention-days: 7
        overwrite: false
        include-hidden-files: true
